version: "3"
services:
    frontend:
      image: frontend
      stdin_open: true
      ports:
        - "3000:3000"
      networks:
        - app
    backend:
        image: backend
        ports:
            - "5000:5000"
        networks:
          - app
networks:
  app:
    driver: bridge
